### ISSUE TITLE
offensive memes - aliencaocao - request for submission runtime

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#10]
Hi,

May we request for the exact runtime of our recent submission  d55aef7c-3c5e-4388-b79b-24581fe3a818 ? The timestamp on website is inaccurate since it includes all the overheads which we cannot predict.

Thank you

**Comment by AISG-Wesley** [comment]
Hi aliencaocao, thank you for the request, we will not be releasing the exact runtime of the submissions.

**Comment by aliencaocao** [comment]
notex with thanks.
