### ISSUE TITLE
JK-Piece-JK-Piece-The logs do not show any error in my code

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#13]
Hi, thanks for providing the logs for my submission `535ae95e-7513-458c-a72d-016cce3fd8bf`.
However, there is no error. I can only see a warning which comes from the images themselves. Below are some of the warnings I can see:

First, there was this warning in my previous submission  `bdd790f6-47b1-4fe6-abdb-32ecc30fe5bb`:
`"libpng warning: iCCP: known incorrect sRGB profile"`. 

Then, I fixed it by installing imagemagic: `RUN apt install imagemagick-6.q16` was added to my Docker file.
Afterwards, I used `os.system(f"convert {image_path} /tmp/img.png")` to convert input images. Next, I use the new file `"/tmp/img.png"` instead of the original one.

Now in my recent submission for which you sent the logs, the following warning occurs:

``` "convert-im6.q16: CorruptImageProfile `/images/d0fdb61ae1bb65fa49a5747b7faa3fbf.png' (XMP) @ warning/profile.c/ValidateXMPProfile/1675."],
       ["convert-im6.q16: CorruptImageProfile `/images/293bb2aec900fb3f9753248e00f4a8b5.png' (XMP) @ warning/profile.c/ValidateXMPProfile/1675."],
       ["convert-im6.q16: CorruptImageProfile `/images/04583003b0a23c09c0f580247c16b6e8.png' (XMP) @ warning/profile.c/ValidateXMPProfile/1675." ```
       
So my point is that there is no error, but only warnings. Can you please assist with this? 

Is it the case that the platform considers warnings as errors?

**Comment by AISG-Wesley** [comment]
We have discovered an issue on our challenge platform and have rectified it.  We will be refunding you for these two submissions:
 
1. `535ae95e-7513-458c-a72d-016cce3fd8bf`; and
2. `bdd790f6-47b1-4fe6-abdb-32ecc30fe5bb`.
 
Our apologies for the inconvenience.
