### ISSUE TITLE
offensive memes - aliencaocao - is there a private leaderboard?

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#14]
Hi,
I noticed the phrasing 'public leaderboard' on the challenge's website. Will this challenge have a private leaderboard like kaggle competitions? Or is the top 5 of the public leaderboard the only citerial of entering the finals?

**Comment by AISG-Wesley** [comment]
Hi Aliencaocao, the nomenclature is an artefact of the challenge platform. For all intents and purposes, the finalists will be determined based on the leaderboard displayed on the challenge website, subject to the outlined [terms & conditions](https://ospc.aisingapore.org/terms-and-conditions) of the Challenge.

**Comment by aliencaocao** [comment]
Thanks for the clarification
