### ISSUE TITLE
AIris - mio - Submission System Issue: Upload Failures and Submission Limits

### ISSUE THREAD

**Issue by mio2333** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#16]
### Issue Description
Despite multiple attempts to upload our Docker image file, each over 20GB in size, we have encountered repeated failures due to network instability. Unfortunately, each failed attempt is still being counted against our submission limit. Attached below is a screenshot documenting our three unsuccessful submission attempts.

<img width="989" alt="image" src="https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/assets/74481573/f34ef617-5ce2-48f6-93eb-b3d6ca9f6d04">

### Concern
This situation presents a significant challenge for our team and potentially others, as there seems to be no guaranteed method for successfully uploading such large files in a single attempt. The current system, which penalizes teams for failed upload attempts due to network issues, appears to be an unfair aspect of the competition, as it affects teams differently based on their internet connection quality, which we believe contradicts the intended competitive spirit and fairness of the OSPC.

### Suggested  Solution
We propose that the submission count should only be incremented upon a successful upload, rather than at the initiation of the upload process. This change would alleviate the undue penalty on teams facing technical difficulties beyond their control and ensure a level playing field for all participants.

we understand that this forum is intended for technical issues, if the request is not suitable here, we will try to email prizechallenge@aisingapore.org instead. Thanks for your consideration.

**Comment by AISG-Wesley** [comment]
Hi mio2333, we understand your frustration in the upload process and have considered your suggestion.
 
Each incomplete upload consumes resources on the challenge platform, and the quota is set around mitigating repeated attempts to perform the same upload process on the same proven to be unstable network connection.
 
We find that it is the participants' responsibility to work out the best way that they can upload their submission, and will not be changing this manner of counting quota.

**Comment by mio2333** [comment]
Ok,I understand. Appreciate your reply.
