### ISSUE TITLE
something - Aradhye2002 - Output format error

### ISSUE THREAD

**Issue by Aradhye2002** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#23]
I am getting an output format error on submitting. However I have used the main.py in the sample_submission only, making changes to the classifier(., .) function. I have also verified that the output is correct by running the container locally.

Could you please send over the logs and convey what exactly is the reason for an output error?

Thanks

**Comment by AISG-Wesley** [comment]
Hi Aradhye2002, could you specify the submission id that you require the logs for please.

**Comment by Aradhye2002** [comment]
Hi Wesley,

The submission id is: 
fb331bb1-26d1-4c51-8c1a-a353a06ef9c0

Thanks

**Comment by AISG-Wesley** [comment]
Hi Aradhye2002, the logs have been sent separately to the email address registered to your account.
