### ISSUE TITLE
Output format error for team goldbach

### ISSUE THREAD

**Issue by goldbach7** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#24]
Could I get the logs for team goldbach, for the recent run with output format error? Thanks

**Comment by goldbach7** [comment]
For run c26b532e-2c93-424f-8551-b80cc93879d2

**Comment by AISG-Wesley** [comment]
Hi golbach, we will not be able to release the log information for this submission as the logs contain information that could compromise the integrity of the dataset. 

However, to assist with your issue, please note that we will not be able to handle partial credit. Each line from stdin must correspond with an output from stdout. More information can be found in this [section](https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#solution-output-stdout) of the submission guide.

**Comment by goldbach7** [comment]
Understood, thank you!

**Comment by Aradhye2002** [comment]
@goldbach7 could you figure out the reason for output error? I am also facing the same problem. Maybe our cases are similar.

**Comment by goldbach7** [comment]
hi @Aradhye2002 as pointed out by the AISG team, make sure that the final output from stdout has the right format and right number of lines as stdin.
