### ISSUE TITLE
offensive meme - aliencaocao - request for logs

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#27]
Can we request for logs for 43f6ef3d-7a5e-46f7-8a0c-6678f6ec2c30, thanks

**Comment by AISG-Wesley** [comment]
Hi aliencaocao, we will not be able to release the logs for this submission as it reveals sensitive information about the dataset.

**Comment by aliencaocao** [comment]
Is it possible for you guys to redact whatever sensitive to you and send the rest? We cannot reproduce any error on our end for our recent 5 submissions so it has been very confusing for us. Thanks

**Comment by AISG-Wesley** [comment]
No, we will not do that.  However, as a one-time effort to assist you, we will release the following summary to what we see in `stderr`, making no guarantees that this is an actual cause.

There were several instances of warning messages of the form `Box coordinates are not in the correct order`.

There was one error message involving `cv2.resize` that was an assertion failure involving `!ssize.empty() in function 'resize'`.

We will not release any more information about the logs from `stderr` for this submission.

**Comment by aliencaocao** [comment]
Thank you. As a follow up technical question, do you have more info on the detailed specifications of your input images? E.g. Format is PNG, are they all 8bit RGB or do some have alpha channel? Are they stored with any special compression?
Based on the error you released to us (which we cannot reproduce over 2000+ scraped png files), it means opencv has failed to read the image. We suspect a data source issue so would like to check if we can get more specifics on the input images. Thank you.

**Comment by aliencaocao** [comment]
Thank you. As a follow up technical question, do you have more info on the detailed specifications of your input images? E.g. Format is PNG, are they all 8bit RGB or do some have alpha channel? Are they stored with any special compression?
Based on the error you released to us (which we cannot reproduce over 2000+ scraped png files), it means opencv has failed to read the image. We suspect a data source issue so would like to check if we can get more specifics on the input images. Thank you.

Or, has the input image been changed anyway since our first submission on 21 feb 3am? Like possibly due to a fix that the other team mentioned? As far as we know, the code that triggered these errors did not change from then to now, yet we are getting them repeatedly.

**Comment by AISG-Wesley** [comment]
No.  We do not do anything special to the `PNG` files.  As at now, not being able to read some subset of the files is currently an isolated issue with your team's submission.

Due to an error in data processing, some image files in the dataset were not in the `PNG` format. This has been rectified and can only make submissions more likely to succeed than not, using only the assumptions we provided.

**Comment by aliencaocao** [comment]
I see. Thank you for the clarification.
