### ISSUE TITLE
Baseline - petergro - Change tmpfs tmp mount?

### ISSUE THREAD

**Issue by petergro-hub** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#29]
Hello dear challenge team,

I wanted to test some local solution on the server but I've run in a bit of an issue. Docker has had a bug with mounting tmpfs volumes, making them non-executable (despite being marked as such) for the past 7 years or longer, see https://github.com/moby/moby/issues/35890 or https://github.com/moby/moby/issues/35890 .
For the solution however I'd like to run libraries from the /tmp folder. Therefore I would like to ask if containers could be executed with `--tmpfs /tmp:exec` instead of `--mount type=tmpfs,destination=/tmp,tmpfs-size=5368709120,tmpfs-mode=1777` or some folder be mounted with something else other than tmpfs, or any other solution that allows files to be executed from a folder.

Thank you and best

**Comment by AISG-Wesley** [comment]
You may run whatever command on your local set up for Docker to test your submissions.

We will, however, not change the invocation options for the challenge environment.  It is recommended that your container, on submission to the challenge platform, be capable of running under the prescribed environment.
