### ISSUE TITLE
offensive memes - sheepymeh - Request for logs

### ISSUE THREAD

**Issue by sheepymeh** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#3]
I'd like to request logs from our run `a35d3475-37b0-4029-9002-b8bcbd7771ea`. We believe that it was a CUDA OOM. We'd like to confirm whether this was the case, and whether the container was able to generate any outputs. Thank you.

**Comment by AISG-Wesley** [comment]
Hi Sheepymeh

Please find our answers to your questions in bold below:

1. Was there a CUDA OOM? 
**No.**

2. Was the container able to generate any outputs?
**No output was generated in stdout**

We will send the logs separately to the email address registered to your participant account.

**Comment by sheepymeh** [comment]
Thank you very much for the prompt response and support!

**Comment by sheepymeh** [comment]
Could we request logs for our new run as well? Thank you.

**Comment by mtmak-aisg** [comment]
Please open a new issue for a new query.
