### ISSUE TITLE
offensive memes - aliencaocao - unable to submit

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#31]
![image](https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/assets/20109683/cc329305-e2fa-4171-94bc-6597c405f947)
It is way past this time yet we still cant submit

**Comment by AISG-Wesley** [comment]
The calculated deadline is correct, however, the page does not auto-refresh.

Please let us know if you still cannot make a submission attempt now.

**Comment by aliencaocao** [comment]
We can now, we did try to refresh it repeatly. Seems like it's just delayed by a day
