### ISSUE TITLE
Baseline - petergro - Request for clarification

### ISSUE THREAD

**Issue by petergro-hub** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#36]
Hello,

I received a 'load docker image error' on fbccd43f-887b-4bed-9a4c-bbf1896c9364 I would like to request clarification on why that is/what the errors were. From my tests it should all be within the challenge limitations.

Thank you

**Comment by petergro-hub** [comment]
Quick ping about this issue, as I had two open at the same time (and the other one was answered), it might have gone unnoticed. Let me know if you need any other information from my side.

**Comment by AISG-Wesley** [comment]
The error indicates that the Docker in the challenge environment has failed to load your image. Following investigations we have found evidence consistent with an intermittent storage size issue.

We have mitigated this by doubling the provisioned storage size. We will be refunding your submission and it will not count towards your quota.

**Comment by petergro-hub** [comment]
Thank you for the clarification
