### ISSUE TITLE
UQ-GD Team Request for Logs

### ISSUE THREAD

**Issue by Stefano-Civelli** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#37]
Hi, Could we please have the logs for submission e4f0c282-6f41-425d-b461-a925ffb5401b ?
We are probably having problems with running code on the GPU because everything works when we run the container locally (we are using the CUDA base image from nvidia). Are there any known incompatibilities with keras_ocr?

Could we also get feedback about the output for this same submission? It is formatted correctly when we run the container locally so we were wondering if the container is just crashing or if the output is incorrectly formatted. 

Thanks

**Comment by AISG-Wesley** [comment]
We cannot advise participants on what libraries are compatible/incompatible to the challenge environment.  Your best option is to use your submission quota wisely to obtain concrete information via logging to `stderr` to guide your actions.

Do take note that we may not release the information logged to `stderr` if we think that it has information that can leak information about the dataset.

To assist you this once, we will highlight that there was no output to `stdout`.

**Comment by Stefano-Civelli** [comment]
What about the logs for submission e4f0c282-6f41-425d-b461-a925ffb5401b ? Do they contain too much information for them to be sent to us?

**Comment by AISG-Wesley** [comment]
Hi Stefano-Civelli, logs have been sent separately to the email address registered to your team leader's account.

**Comment by Stefano-Civelli** [comment]
Thank you very much!
