### ISSUE TITLE
GPU Compatibility on Submission Platform - UQ-GD

### ISSUE THREAD

**Issue by Stefano-Civelli** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#38]
Hi, I'm from the UQ-GD team. We are encountering GPU compatibility issues on the challenge platform, affecting our progress. Our code runs on a CPU locally, but fails on the platform's GPU environment, likely due to compatibility problems. We're using the Nvidia Docker image with CUDA and cuDNN as specified, yet errors persist.

Could you provide guidance or a GPU-specific code sample? This would allow us to focus on the challenge tasks rather than setup issues.

**Comment by AISG-Wesley** [comment]
We cannot advise participants on what libraries are compatible/incompatible to the challenge environment.  Your best option is to use your submission quota wisely to obtain concrete information via logging to `stderr` to guide your actions.

Do take note that we may not release the information logged to `stderr` if we think that it has information that can leak information about the dataset.
