### ISSUE TITLE
Baseline - petergro - Request for logs

### ISSUE THREAD

**Issue by petergro-hub** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#39]
Dear AISG Team,

I'd like to request the stderr logs for run 415277af-6c4c-4cf4-bf2d-b0b8cf987170

Thank you

**Comment by AISG-Wesley** [comment]
Hi petergro-hub, logs have been sent separately to the email address registered to your account.

**Comment by petergro-hub** [comment]
Thank you
