### ISSUE TITLE
Submission Upload Failed

### ISSUE THREAD

**Issue by shshen-closer** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#41]
Hello, I want to ask if "Submission Upload Failed" takes up team's submission quota?  I hope not, since the network fluctuation is easy to occur when uploading the submission.

**Comment by AISG-Wesley** [comment]
Yes, this failed upload will consume the team's submission quota.  Please see our previous response to a similar issue in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/issues/16 .

Each incomplete upload consumes resources on the challenge platform, and the quota is set around mitigating repeated attempts to perform the same upload process on the same, proven to be unstable network connection.

It will be the participants' responsibility to work out the best way that they can upload their submission, and we will not be changing this manner of counting quota.

**Comment by shshen-closer** [comment]
Thanks for your reply. However,  could you please exclude my previous submission that faced submission upload failed? I wrongly thought that it would not take up the quota,  as it seems that only successful submissions will be counted in the Leaderboard. I also missed your response to the previous issue. In the following, I will turn to a better network environment.

**Comment by AISG-Wesley** [comment]
Hi shshen-closer, in the spirit of fairness, we will not be refunding the submissions for this. You will have more submissions to utilise throughout the duration of the challenge and we encourage you to iterate on your solution while waiting for them to become available.

**Comment by shshen-closer** [comment]
Thanks for your reply!
