### ISSUE TITLE
JK-Piece -- Request for logs

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#46]
Can you please provide logs for the following two submissions

1-)  7b4f3fe5-b6e0-4ad6-b456-07714b7b2ab0

2-) c7640ddd-a8a8-4124-8aa6-dac63161656d

Thanks.

**Comment by AISG-Wesley** [comment]
Hi Jean-KOUAGOU, as mentioned previously, could you create a separate issue for the log request of the second submission. Thanks. 

I will be sending the first log to the email registered to your account.

**Comment by Jean-KOUAGOU** [comment]
Thanks. I do no longer need the logs for the other submission. I am closing this issue
