### ISSUE TITLE
offensive memes - aliencaocao - docker run specs

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#47]
Hi,
We note that in readme you use
```
ISOLATED_DOCKER_NETWORK_NAME=exec_env_jail_network

cat local_test/test_stdin/stdin.csv | \
docker run --init \
        --attach "stdin" \
        --attach "stdout" \
        --attach "stderr" \
        --cpus 2 \
        --gpus "device=0" \
        --memory 4g \
        --memory-swap 0 \
        --ulimit nproc=1024 \
        --ulimit nofile=1024 \
        --network exec_env_jail_network \
        --read-only \
        --mount type=bind,source="$(pwd)"/local_test/test_images,target=/images,readonly \
        --mount type=tmpfs,destination=/tmp,tmpfs-size=5368709120,tmpfs-mode=1777 \
        --interactive \
        sample_container \
 1>local_test/test_output/stdout.csv \
 2>local_test/test_output/stderr.csv
```
Which limits the docker to only 2 cpus and 4gb RAM, while the technical spec listed is 6cpu and 60GB RAM. Which is accurate at evaluation?

**Comment by AISG-Wesley** [comment]
Please note that in the readme, the section you pulled this information from is https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#test-sample-docker-container-locally or https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#5-test-your-container-using-docker-run , which are both **samples** on how to run the Docker container locally.

We understand your frustrations, but considering that more than 20 teams have valid submissions on the leaderboard (including your team), with at least 7 beating the best baseline as at time of writing, we think that the instructions are sufficiently clear in terms of which is accurate at evaluation.

However, we will link to the relevant section again to address the direct question: https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#technical-details .

**Comment by aliencaocao** [comment]
Thanks, just needed the confirmation.
