### ISSUE TITLE
Offensive memes - aliencaocao - On handling of TLE

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#48]
Hi, we would like to know if a docker does not quit itself for some reason but all the stdout are already complete for each line of stdin and in the right format, does this become a time limit exceeded or output format error?

Is there anyway AISG could take whatever outputted at end of 2.5hrs runtime and check if it is the right format?

**Comment by AISG-Wesley** [comment]
If your container fails to terminate at the end of the time limit, you will incur a Time Limit Error.

There is no reason why any container should continue running after all the necessary output to `stdout` has been generated for each input in `stdin`. Most programming languages have a way of testing for the `EOF` condition for `stdin`, and it should be considered as the expected approach for the I/O conditions stipulated in the challenge ( https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#dataset-input-output ).

As to your second question: no,

**Comment by aliencaocao** [comment]
The reason here being we have background processed that does not exit itself cleably. We will find a way around it then, thanks

**Comment by aliencaocao** [comment]
The reason here being we have background processed that does not exit itself cleably. We will find a way around it then, thanks
