### ISSUE TITLE
offensive memes - aliencaocao - Evaluation timing

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#5]
Hi,

We noticed that the submission shows as running even when the backend is extracting the docker image. Does that count into our 2.5hr of runtime, or is that 2.5hr starting from the launch of docker container?

**Comment by AISG-Wesley** [comment]
As per the wording at https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#max-docker-container-runtime, the 2.5 hours is only applicable to your solution's run-time, excluding other necessary overheads.

**Comment by aliencaocao** [comment]
Thanks for the answer
