### ISSUE TITLE
R2Studio - huyenbk_vinuni - Submission failed

### ISSUE THREAD

**Issue by huyenbui117** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#53]
Hi, I've encountered an issue where my last 4 upload attempts on the same device have been unsuccessful, which is puzzling since I've had successful uploads previously. Additionally, these unsuccessful tries are being deducted from my total submission quota, which is a waste of resource. Could these failed attempts possibly be removed from my submission count?

**Comment by AISG-Wesley** [comment]
Hi huyenbui117, we understand your frustrations. Upon reviewing our system, we have not detected any issues with our infrastructure, and other participants have been able to make their submissions successfully around the same timeframe. This might suggest that the problem could be specific to the circumstances of your submissions.

In the spirit of fairness, we cannot alter submission counts without evidence of a technical issue on our end. We encourage you to try again once your quota refreshes.
