### ISSUE TITLE
Offensive memes - aliencaocao - question on hardware performance of VM

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#59]
Inspecting our logs and comparing with our own testing done in a local server running:
Ubuntu 22.04 LTS
Intel Xeon Gold 6142 @ 2.4Ghz (limited using `--cpus 6` when running docker)
Nvidia V100 PCIE 16G
60GB RAM (also limited using docker)
a pcie3.0 SSD

We realise that the inference speed on the AISG infra was 2-4 times slower for the same output/amount of FLOPS, thus causing our solution to exceed time limit. This happens across 3 different libraries we use (each uses a different set of underlying CUDA code)

We would like to check if AISG has done any performance testing/comparsion of the solution runner to a local hardware, and if there are explanations for this observation that other teams also has observed. I understand that virtualization, if any, could cause performance loss but at this scale and across different libraries, sounds too much.

Model loading was also twice as slower but I can attribute that to a possbily slower SSD.

It would be more beneficial if AISG could provide the specs as shown within the OS (e.g. /proc/cpuinfo), as AWS dont provide them publically.

Our team is happy to provide evidence and logs of our performance testing and how we concluded that it is a fair comparsion via email.

**Comment by AISG-Wesley** [comment]
We have no intention of being more specific with the specifications other than what has already been published in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide .

The intention of this Prize Challenge as stated in https://ospc.aisingapore.org/ is clear: we aim to advance research in developing multimodal, multi-lingual, zero-shot models that distinguish between benign and harmful memes relevant to the Singaporean context.

As such, we have always left the choice of approaches, methods, algorithms, and software libraries to the participants, while emphasising the need to be cognizant of the Prize Challenge environment (see "Guidelines on Model & Docker Container Formats" under https://ospc.aisingapore.org/technical-details ).

Participants are encouraged to be strategic in their use of the submission quota system to learn more of the operating environment with respect to their solutions, and to adapt their solutions accordingly.

**Comment by aliencaocao** [comment]
Ok I think we can just take it that the V100 on the infra is slower. We will make adjustments accordingly. Thanks
