### ISSUE TITLE
offensive memes - aliencaocao - Request for CPU model specification

### ISSUE THREAD

**Issue by aliencaocao** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#6]
Hi,

We are interested in using some cpu specific optimizations that is only supported by newer cpus. Thus we would like to check what is the exact model of the runtime's CPU.

Thanks

**Comment by AISG-Wesley** [comment]
Hi aliencaocao,

According to the documentation of the infrastructure provider, the CPU is an Intel Xeon ES-2686 v4 (see p284 of https://docs.aws.amazon.com/pdfs/ec2/latest/instancetypes/ec2-types.pdf ).  But do take note of the following three caveats:
 
1. The information is provided by the infrastructure provider, and we make no guarantees about the available features of the CPU as used in the challenge platform.
 
2. The challenge is designed around using better approaches/models/algorithms, and not on low-level optimisation for specific hardware to be in compliance with §8 of https://ospc.aisingapore.org/terms-and-conditions .
 
3. The resource allocation specified in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#hardwaresoftware-specifications holds regardless of what the underlying hardware is, and we have no intention of changing said allocation.

**Comment by aliencaocao** [comment]
Thank you for the info
