### ISSUE TITLE
Request for logs

### ISSUE THREAD

**Issue by casuse0001** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#61]
I would like to request the stderr logs for **72980043-b475-4bf6-ae13-a4fb01e0fc2e** - sample_container by team **cas0001** along with the stats for test cases that are failed or passed before 'Time Limit Exceeded' error.

Thanks,

**Comment by AISG-Wesley** [comment]
Hi casuse0001, logs have sent to the email registered to your account. We will not be releasing any outputs from `stdout` nor any stats regarding your test cases before the `Time Limit Exceeded` error was incurred.

Please ensure that you follow the posting conventions outlined in #1 for future issues.
