### ISSUE TITLE
TrumorBERT - jackal_1586 - Request for logs

### ISSUE THREAD

**Issue by Jackal1586** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#62]
Hi can you kindly send me the logs generated in this run:  91f18361-eb2c-4687-8c8b-90146439e13e .

Thank you.

**Comment by AISG-Wesley** [comment]
Hi Jackal1589, we will not be able to release logs for this submission as it contains information that could compromise the integrity of the dataset.

**Comment by Jackal1586** [comment]
Ok, understood.
