### ISSUE TITLE
Baseline - petergro - submission failed

### ISSUE THREAD

**Issue by petergro-hub** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#66]
Hello, could you please check if there was a glitch in the submission system today towards ~10:50 GMT+1 time? as I was submitting, the website just crashed for me, no other open tab, nor my pc & my connection was stable. I've had failed submissions before, but this time I am clueless as to why it would be. Also this was a rather crucial upload.

**Comment by AISG-Wesley** [comment]
Hi petergro-hub, we understand your frustrations. Upon reviewing our system, we have not detected any issues with our infrastructure during that time. 

In the spirit of fairness, we cannot alter submission counts without evidence of a technical issue on our end. We encourage you to try again once your quota refreshes.
