### ISSUE TITLE
Request for more details on errors - JKPiece

### ISSUE THREAD

**Issue by Jean-KOUAGOU** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#7]
My recent submission ran for approximately 2 hours, then displayed "Error". Would it be possible to provide more details on the error so I can make a valid submission?

Fingerprint:  8d6d871d-cbf4-456c-a52d-89af458ba549

**Comment by AISG-Wesley** [comment]
Hi Jean-KOUAGOU, 

Thank you for the request. We will send the logs separately to the email address registered to your participant account.

**Comment by Jean-KOUAGOU** [comment]
Thank you for the answer. I received the logs and fixed what was the problem. Now there is another unknown error. Did the submission exceed the runtime limit, I am not sure. It ran longer this time.

Can you please provide the logs again? Thanks

Submission fingerprint:  bdd790f6-47b1-4fe6-abdb-32ecc30fe5bb

**Comment by mtmak-aisg** [comment]
Please use a new issue for a new query.
