### ISSUE TITLE
Submission Upload Failed - Meme Guardians

### ISSUE THREAD

**Issue by harisbinzia** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#70]
Dear Organizers, 

We are continuously facing the submission upload failed error since our last successful submission. All these submissions failed when the submission upload progress reached over 90%. I would be grateful if you could help us trace down the issue or suggest a workaround because, without a successful upload, we are not able to proceed in the competition. 

Here are the submission IDs:

- 28f69864-6781-4bcf-8e7f-54b87a14e59b
- 6455aa55-57da-4258-8393-fa5680d9f4ef
- 93d643b7-8b48-4703-a2cc-bfb8bcc0a054
- a9948efb-6aec-44e0-9b80-c8bb92aac354
- 22a4953e-779c-4f27-8eb0-aedf7e1b050e

Note: We have already tried changing browsers and internet connections and we don't close and switch tabs during upload.

**Comment by AISG-Wesley** [comment]
Hi harisbinzia, we understand your frustrations. Upon reviewing our system, we have not detected any issues with our infrastructure during the time of your submissions. This might suggest that the problem could be specific to the circumstances of your submissions.

In the spirit of fairness, we will not be able to refund these submission without evidence of a technical issue on our end, and encourage you to try again.
