### ISSUE TITLE
Humans of DSCIG - bramyeon - Submission Upload Failed

### ISSUE THREAD

**Issue by bramyeon** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#74]
Dear AI Singapore,

Our team has encountered 2 consecutive failed uploads throughout the weekend and we could not make any proper submissions due to this recurring issue. 
**Submission IDs:** `a52d0dc6-77d6-4f9b-ad15-802154634301`, `8e6a4fa4-e727-4c0a-bc89-2f5faede48b4`
Interestingly, both failed submissions stopped at ~80% progress despite having different docker image contents and sizes. 
Our internet connection was stable throughout the upload and we did not close or switch to another page during the process.
We have sent 2 (two) emails to prizechallenge@aisingapore.org (from the email address registered for bramyeon) and provided all the details we could in the emails. 
Could you please check them out?
Thank you in advance for your time!

**Comment by AISG-Wesley** [comment]
Hi bramyeon, we understand your frustrations. Upon reviewing our system, we have not detected any issues with our infrastructure during the time of your submissions. This might suggest that the problem could be specific to the circumstances of your submissions.

In the spirit of fairness, we will not be able to refund these submission without evidence of a technical issue on our end, and encourage you to try again.
