### ISSUE TITLE
UQ-GD - Submission Upload Failed

### ISSUE THREAD

**Issue by Stefano-Civelli** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#75]
Dear AI Singapore,
Our upload of 15fafc69-ab91-4002-aa07-aed5ff6e9f3e is currently stuck at 98%. It's not giving any error and the connection is stable. We did not close it or switch to a different page. In the next few hours, we will have to stop it and therefore lose the submission. Could you look into the issue?

Thank you.

**Comment by AISG-Wesley** [comment]
Hi Stefano-Civelli, we have noted that you were able to subsequently upload a successful submission. With regards to the previous unsuccessful submission `15fafc69-ab91-4002-aa07-aed5ff6e9f3e`, we have not detected any issues with our infrastructure during the time of the submission. This might suggest that the problem could be specific to the circumstances of your submission. In the spirit of fairness, we will not be able to refund this submission without evidence of a technical issue on our end. We appreciate your understanding.
