### ISSUE TITLE
N is not NP - JvJv - Submission Upload Failed

### ISSUE THREAD

**Issue by JvJvless** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#82]
Hi, I encountered an issue with upload failure. After some local tests and upload tries, I have determined that I am unable to resolve this issue on my own. Now our team only has one last chance to submit but no any successfully submittion, so I am seeking your help.

I tried to submit my submission 6 times, but failed in 5 times when upload:
- 3c2346be-e9a4-4c18-ae40-d6c0ce24eb6f
- d787a5ae-d91f-476c-a9c4-454d00390c2d
- 889471fc-39f1-43f4-b41c-ccbc42661692
- cb2c876d-5a77-477b-8e2e-ba7d5582ba5f
 - de0908ad-3f59-4efa-a4a0-b092fe06263a

I noticed that many people are facing similar problems, so first I tried to adjust my network environment.
In the second to last attempt, the network I was using only had an upload bandwidth of about 10mbps. After waiting for about an hour, when the upload reached around 38%, the connections suddenly interrupted and the upload failed.
Therefore, in the last attempt, I switched to a network with an upload bandwidth of about 200Mbps. Although it was faster, when the upload reached 38%, all connections were interrupted and the upload failed.
This seems to have some unusual correlation.

In order to provide more specific information, I have kept a screenshot of the last upload.
![38cb5169eb753f625b56ff97aa13a114](https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/assets/42237917/924418c5-cb25-4cf8-885c-bbbcc7fc4030)
![5199add687cc6fadbf96d19e71354f5b](https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/assets/42237917/d89c731c-fb30-4064-88a3-346a546d8edc)
The first image shows the situation at the beginning of uploading, and the second image shows the situation when all connections are interrupted. For personal privacy reasons, I have smeared some of the content in the picture.
Specifically, when the upload reaches 38%, the progress suddenly stops and all connections related to the upload disappear.
I ensure that I do not take any unnecessary actions during the waiting period, such as closing or refreshing the page.

My appeals are
1. Rollback our team's failed submissions due to unknown network errors, at least for the last time
2. Provide more specific details about uploading (for example, how the uploaded connections keep) to help us identify and solve problems, rather than *encourage you to try again* (or wasting our last chance)

We hope to truly participate in this competition, rather than wasting all our efforts : (

**Comment by AISG-Wesley** [comment]
Hi JvJvless, we understand your frustrations. Upon reviewing our system, no issues were detected with our infrastructure during the time of your submissions. This might suggest that the problem could be specific to the circumstances of your submissions.

In the spirit of fairness, we will not be able to refund these submission without evidence of a technical issue on our end. Reasons for our stance have been outlined in previous issues (#41). We appreciate your understanding.

**Comment by JvJvless** [comment]
@AISG-Wesley Thank you for your reply, but could you provide details about the file upload technology used in the competition platform to help me identify the problem.
I understand your anxiety when facing a large number of such issues, so you can only provide a unified and lack effective information response. But this does make the majority of participants facing this problem believe that you have chosen to ignore this situation and have not made any efforts to help improve the problem. 
In my issue, I have attached the specific situation I encountered, hoping that it can help you understand and find the relevant problems. I hope you don't overlook this content just because of the title.
I fully understand your requirements and statements regarding fairness, so I no longer request to rollback my submissions, but I still request more possible information about this problem.

**Comment by AISG-Wesley** [comment]
Hi JvJvless, thank you for the reply. Given that this is an international challenge, we cannot account for all possible connectivity issues faced by participants. As mentioned, our infrastructure remained stable during the time of your submissions, and unfortunately, we are unable to offer specific advice regarding your connectivity issues.
 
However, we appreciate you bringing this matter to our attention. Understanding such situations will help us consider improvements to accessibility for future challenges.

**Comment by JvJvless** [comment]
Okay, thank you. Wishing you all the best in your future challenges.
