### ISSUE TITLE
R2Studio - request for log

### ISSUE THREAD

**Issue by phuong-dinhmai** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#85]
Dear AISG team,
Could I get the log of 2 submissions a095e2a4-2daf-4fd0-a406-91abbc3ac23d and 862fbfc9-6c59-4ffd-b46d-7d4dd2430013?
Thanks for your help in advance.

**Comment by AISG-Wesley** [comment]
Hi Neko1122000, logs have been sent to the team leader's email.
