### ISSUE TITLE
Baseline - petergro - request for resubmission

### ISSUE THREAD

**Issue by petergro-hub** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#89]
Dear AISG,
Due to the issue with #36 my submission setup (submit every 2 weeks, so that I could submit one more time before the deadline) was disrupted, as the resubmission was only allowed 3-4 days after I opened the request. Meaning my submission (which would've been planned for yesterday) is now only allowed on the 13.
I would request to make a submission deadline be moved by the delay it took for it to be reuploaded for this reason, as this was purely out of my control & related to a server mistake.

Originally I had not planned to write about it, but due to the mysterious 5 recent timeouts, including the most recent one, (local solutions on separate V100 taking maybe  2-4s per sample, but time-outing on the servers) and the extreme sparsity in allowed submissions, I have not been able to submit & would like to have a final submission, even if it might not be better. 

Thank you for considering this.

**Comment by AISG-Wesley** [comment]
We understand your concerns and have carefully considered your request. However, after thorough review, we regret to inform you that we are unable to grant it. We appreciate your understanding in this matter and thank you for bringing this issue to our attention.

**Comment by petergro-hub** [comment]
Thank you for the quick answer. I believe that it is within the intentions of the challenge to allow for a fair environment, which is why I understand & appreciate the necessity of not considering errors & strict abidance by the rules.
In this case however, I would like to plead for the fact that my intended participation was directly hindered by a system error on the challenge organizers' side, which has basically removed a submission opportunity for me compared to any other participant.
If you check my submission log (and please check it entirely), I have submitted 6 solutions up to the 13.03.2024. That is because one submission was within that timeframe but errored out, due to a mistake on the challenge processing part, not allowing me to submit anymore. Originally this was planned for the 14.
The server error on your side got resolved later, at which point I was already past the 2 weeks schedule I had planned out. (at the latest on 14th - 28th - 11th)
If you go through my submissions, you can see that they are all timed so that I can submit one more time, perfectly before the deadline (as I had planned when going for this challenge), always except for one (16th-30th-now 14th), originally caused by the server error. Which would make it exactly 21.
I believe given these submissions, it clearly means that I have had one possible submission less compared to other teams.
So I would please ask you reconsider, as this is a fault purely on the organization side, not because of the server error, but because of the delay it took to remove that error.

I am aware this is an unusual request, but given the extremely limiting circumstances of this challenge, submission management was (in my eyes) an extremely important aspect of the challenge (as I believe many of the raised issues testify). Issues stemming from a organizatorial mistake / delay, should therefore not be put to the challenger's detriment. I also understand that this might be a vain effort for a submission that might just end up being worse.

Once again, thank you for considering this.

**Comment by AISG-Wesley** [comment]
We hear your sincere request, and empathise strongly with you.

However, we are literally unable to grant your request due to current system limitations.  The lateness of this request also gives us little room to re-examine these said limitations and come up with mitigating factors that allows us a freer hand in granting exceptions that may be well deserved.

We deeply apologise for this bad news, and hope that the disappointment does not deter you from joining any future Prize Challenges organised by us.

**Comment by petergro-hub** [comment]
In this case there is not much more to be done.
Thank you for the effort invested so far throughout this challenge
