### ISSUE TITLE
JK-Piece - JK-Piece - Can you please provide the logs again? Thanks

### ISSUE THREAD

**Issue by mtmak-aisg** [AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide#9]
Thank you for the answer. I received the logs and fixed what was the problem. Now there is another unknown error. Did the submission exceed the runtime limit, I am not sure. It ran longer this time.

Can you please provide the logs again? Thanks

Submission fingerprint:  bdd790f6-47b1-4fe6-abdb-32ecc30fe5bb

_Originally posted by @Jean-KOUAGOU in https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/issues/7#issuecomment-1954229618_

**Comment by AISG-Wesley** [comment]
Hi Jean-KOUAGOU, 

Logs for the latest submission have been sent to your email. 

Do remember to use only /tmp for writing any temporary files.  For details, please consult https://github.com/AISG-Technology-Team/AISG-Online-Safety-Challenge-Submission-Guide/?tab=readme-ov-file#create-a-main-file .

**Comment by Jean-KOUAGOU** [comment]
Unfortunately, I still cannot get my submission scoring. Here is the new fingerprint (recent submission) for which I would like to have the logs:
 535ae95e-7513-458c-a72d-016cce3fd8bf

**Comment by AISG-Wesley** [comment]
Please submit a separate issue for new queries in future. Thank you. 

You may find my reply to your request at #12
